### ISSUE TITLE
Run the nanoc command from a sub-dir

### ISSUE THREAD

**Issue by bfmartin** [nanoc/features#19]
Similar to how the rake command finds the Rakefile, nanoc should search for the nanoc.yaml file in the current directory, and if not found, then search the parent directories. The directory where the nanoc.yaml file is found will become the current directory for the actions executed in the nanoc command.

**Comment by denisdefreyne** [comment]
I made a PR for this: nanoc/nanoc#1210

I also learned that `bundle exec` will already search for a Gemfile in an ancestral directory!

**Comment by denisdefreyne** [comment]
This will be released in 4.8.3.

**Comment by bfmartin** [comment]
That is really great. Thank you very much.

For the quick response time and also for building such a great project.
