### ISSUE TITLE
title_proc in blogging helper

### ISSUE THREAD

**Issue by denisdefreyne** [nanoc/features#42]
The blogging helper currently has `content_proc` and `excerpt_proc` parameters, which can be used to transform the content and excerpt, respectively, that show up in the Atom feed.

It would be useful to also have `title_proc`, so that the title can be transformed as well. For example, it might be useful to add the date to the title.

**Comment by th-h** [comment]
Looks like some easy copy & paste should solve that, see nanoc/nanoc#1362.

Works for me, but I'm not fluent enough in Ruby to add / expand the test suite ...
